node{
    def mvn = tool (name: 'maven3', type: 'maven') + '/bin/mvn'

    stage('checkout to SCM'){
        checkout scm
    }

    // stage('compile and test'){
    //     sh "cd msgq/ && ${mvn} clean install"
    // }

    stage('Push Rabbit-mq image'){    
        def dockerfile = 'Dockerfile'
            // sh 'docker build -t majidshaikh16/simple-web -f ./msgq/${dockerfile} ./msgq/'
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-creds') {
            def customImage = docker.build("majidshaikh16/rabbit-mq","-f ./msgq/${dockerfile} ./msgq/")
            // customImage.push()
            // customImage.push('staging')        
        }

    }

    stage('stop old and up'){
        sh 'cd msgq/ && docker-compose stop && docker-compose rm -f && docker-compose up -d'
    }
    
}