node{
    checkout scm
     def dockerfile = 'Dockerfile'
        // sh 'docker build -t majidshaikh16/simple-web -f ./SimpleWeb/${dockerfile} ./SimpleWeb/'
    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-creds') {
        def customImage = docker.build("majidshaikh16/simple-web1","-f ./SimpleWeb/${dockerfile} ./SimpleWeb/")
    customImage.push()

    customImage.push('staging')
    }
    
}