apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker-api
  template:
    metadata:
      labels:
        component: worker-api
    spec:
      containers:
        - name: worker-api
          image: majidshaikh16/rabbit-mq-worker-apis:latest
          ports:
            - containerPort: 8086
          env:
            - name: SERVER_PORT
              value: '8086'
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432' 
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD   

# kubectl create secret generic rabbitpassword --from-literal RABBITPASSWORD=guest                                            