server:
  port: ${SERVER_PORT}

# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection

# Connection url for the database "R&D"
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDBNAME}
# Username and password  
    password: ${PGPASSWORD}
    username: ${PGUSER}
    
    
# ===============================
# = JPA / HIBERNATE
# ===============================

# Use spring.jpa.properties.* for Hibernate native properties (the prefix is
# stripped before adding them to the entity manager).

# Show or not log for each sql query

  jpa:
    database: POSTGRESQL
    show-sql: true
# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project
    hibernate:
      ddl-auto: update 
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        
# Allows Hibernate to generate SQL optimized for a particular DBMS
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

SERVER_PORT: 8086
PGHOST: 10.0.60.234
PGPORT: 5432
PGDBNAME: postgres
PGUSER: postgres
PGPASSWORD: root
        
    
        
